sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: k6NVhrHrEkYmcvDvTwcUxHQnY3+nMEFVXtd0gNOJo6WyLRrVF6WQcB6ChVO1eXPGBhXlIDpZ3wy8jXbc2uHZZuWfE415Pdrv6MFEqIdoIAUw2Y1qT2JS3TcU9Gm3y2zhtw6ycn9LQoulMPF3/sSwjJkw9QVhRRM4y4a9N4ypYjwJST88yxteVOTZEwmi6780yHIBAv3a4Yp0EzBDICgNIWOknl4rvaepjP4VVWAaoecXjpR0Wn05nUA3WNU9mIDJyYpkQNJB6IPrxfiq2rXiOETZ/F0MPqgEpWwzLgCRD5Z+HAoBvdlZBXSVUxl2mNeN5uZH2Q87iFzWSB1AWNuhxaL1lpR5So0G7NRP/qSU9lHI7IL+QyTL9WtDpduPQyz7Ax66/ZitQIKidJJDCmKGtIv8BJJA53Uuq80zGZuIqO86Cs2viovNUKr8H8VNiK4+AUWzBzuevr2+zHdBo0imX0pNiJBia8lUWqDyPe+RMZgzp2kivL9YvH16/ey44RhV2bXortWWWIzXzsumQ3a+ci1ISxUWXZ8ToWWTvuoZAormwPFxC/zenDcm+pEbas6uGHKGvVstikZ+huHGG8auwj2nv5Ct6DJCMeNF2SJ2l8AMCYgVkgVKNaF+EigZb3KGvBGUtcqoW2zMhSZjKd/ZngJoxCvk01n5a2pbmE5Rtxo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Group-of-Noble-Dames_3049
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy